Ensure boolean field values are strings before checking casecmp.
I can't find any info on this, but these errors below started when we switched to bundle:

     NoMethodError: undefined method `casecmp' for false:FalseClass
       from /Library/Ruby/Gems/1.8/gems/asf-soap-adapter-1.3.1/lib/active_record/connection_adapters/activesalesforce_adapter.rb:419:in `add_rows'

     NoMethodError: undefined method `casecmp' for true:TrueClass
       from /Library/Ruby/Gems/1.8/gems/asf-soap-adapter-1.3.1/lib/active_record/connection_adapters/activesalesforce_adapter.rb:390:in `select_all'

I couldn't find anything online related to this error so the only way around this was to patch this error.